/* eslint-disable global-require */
const devicesData = [
  {
    article: '0100-492952',
    image: require('../../img/page/1.jpg'),
    image2x: require('../../img/page/1@2x.jpg'),
  },

  {
    article: '0100-491166',
    image: require('../../img/page/2.jpg'),
    image2x: require('../../img/page/2@2x.jpg'),
  },

  {
    article: '0100-494385',
    image: require('../../img/page/3.jpg'),
    image2x: require('../../img/page/3@2x.jpg'),
  },

  {
    article: '0100-492971',
    image: require('../../img/page/4.jpg'),
    image2x: require('../../img/page/4@2x.jpg'),
  },
  {
    article: '0100-492963',
    image: require('../../img/page/5.jpg'),
    image2x: require('../../img/page/5@2x.jpg'),
  },

  {
    article: '0100-498341',
    image: require('../../img/page/6.jpg'),
    image2x: require('../../img/page/6@2x.jpg'),
  },

  {
    article: '0100-498382',
    image: require('../../img/page/7.jpg'),
    image2x: require('../../img/page/7@2x.jpg'),
  },

  {
    article: '0100-498564',
    image: require('../../img/page/8.jpg'),
    image2x: require('../../img/page/8@2x.jpg'),
  },

  {
    article: '0100-498389',
    image: require('../../img/page/9.jpg'),
    image2x: require('../../img/page/9@2x.jpg'),
  },

];

const devicesArray = [
  {
    article: '0100-492952',
    pickupAvailable: true,
    deliveryAvailable: true,
    description: null,
    frontName: 'Смартфон Infinix HOT 30 4/128Gb Racing Black',
    slug: 'infinix-hot-30-4-128gb-racing-black',
    brand: 'Infinix',
    catalogId: {
      productId: 'prod6680004',
      skuId: 'sku6010006',
      serialId: null,
    },
    colors: [
      {
        id: 'spec300007',
        name: 'черный',
        code: '#000000',
        catalogIdData: {
          productId: 'prod6680004',
          skuId: 'sku6010006',
          serialId: null,
        },
        skuSlug: 'infinix-hot-30-4-128gb-racing-black',
      },
      {
        id: 'spec400001',
        name: 'белый',
        code: '#FFFFFF',
        catalogIdData: {
          productId: 'prod6680004',
          skuId: 'sku6010007',
          serialId: null,
        },
        skuSlug: 'infinix-hot-30-4-128gb-sonic-white',
      },
      {
        id: 'spec5900010',
        name: 'зеленый',
        code: '#4de4aa',
        catalogIdData: {
          productId: 'prod6680004',
          skuId: 'sku6010008',
          serialId: null,
        },
        skuSlug: 'infinix-hot-30-4-128gb-surfing-green',
      },
    ],
    images: [
      {
        url: '/api/media/asset?mediaId=m6170117',
        main: true,
        path: 'https://msk.tele2.ru/api/media/asset?mediaId=m6170117',
      },
      {
        url: '/api/media/asset?mediaId=m6170118',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6170118',
      },
      {
        url: '/api/media/asset?mediaId=m6170119',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6170119',
      },
      {
        url: '/api/media/asset?mediaId=m6170120',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6170120',
      },
      {
        url: '/api/media/asset?mediaId=m6170121',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6170121',
      },
    ],
    price: {
      amount: 11790,
      currency: 'RUB',
    },
    salePrice: null,
    discountValue: null,
    url: null,
    barcode: null,
    eventMessage: {
      id: '1400001',
      name: 'Новинка',
      type: 'new',
      iconColor: null,
      icon: 'https://msk.tele2.ru/api/media/asset?mediaId=m4940001',
      description: null,
    },
    categorySlug: 'smartphones',
    promo: true,
    promoCampaigns: [
      {
        id: '2000002',
        externalId: '158',
        name: 'Скидка на смартфоны 500',
        slug: 'smartphones',
        promoTextNotAuth: '500 ₽ скидка – 500 минут ',
        promoPageLink: 'https://msk.tele2.ru/minutes-management/smartphones',
        promoText: '500 ₽ скидка – 250 минут ',
        infoBlockTitle: 'Скидка до 500 ₽ за минуты',
        infoBlockText: 'Скидка за минуты',
        infoBlockIcon: null,
        priority: 100,
        displayType: 'combined',
        labelText: 'Скидка до 500 ₽ за минуты',
        labelTextColor: '#C882FF',
        labelBackgroundColor: '#F4E5FF',
        tooltipText: 'Обменяй минуты на скидку на устройства.',
      },
      {
        id: '1400002',
        externalId: '15',
        name: 'Комбо 1.0 (-50%)',
        slug: null,
        promoTextNotAuth: 'при покупке комбо 3 в 1',
        promoPageLink: 'https://msk.tele2.ru/promotions/article/discount-infinix-smartphones/discount-infinix-smartphones',
        promoText: null,
        infoBlockTitle: 'Скидка за комплект',
        infoBlockText: 'При покупке смартфона, SIM-карты и страховки',
        infoBlockIcon: 'https://s3.tele2.ru/ds-site/images/shop/combo/50-sale-bage.svg',
        priority: 360,
        displayType: 'text',
        labelText: null,
        labelTextColor: null,
        labelBackgroundColor: null,
        tooltipText: null,
      },
    ],
    saleVariants: [
      {
        catalogId: {
          productId: 'prod6820001',
          skuId: 'sku6140006',
          serialId: null,
        },
        skuType: 'comboSku',
        promoCampaigns: [
          {
            id: '1400002',
            externalId: '15',
            name: 'Комбо 1.0 (-50%)',
            slug: null,
            promoTextNotAuth: 'при покупке комбо 3 в 1',
            promoPageLink: 'https://msk.tele2.ru/promotions/article/discount-infinix-smartphones/discount-infinix-smartphones',
            promoText: null,
            infoBlockTitle: 'Скидка за комплект',
            infoBlockText: 'При покупке смартфона, SIM-карты и страховки',
            infoBlockIcon: 'https://s3.tele2.ru/ds-site/images/shop/combo/50-sale-bage.svg',
            priority: 360,
            displayType: 'text',
            labelText: null,
            labelTextColor: null,
            labelBackgroundColor: null,
            tooltipText: null,
          },
        ],
        salePrice: null,
      },
    ],
  },
  {
    article: '0100-491166',
    pickupAvailable: true,
    deliveryAvailable: false,
    description: '<p>Смартфон Infinix HOT 30 8/128Gb - это мощное и функциональное устройство с большой памятью и высокой производительностью. Он оснащен 6,7-дюймовым IPS-дисплеем с разрешением 2460x1080 пикселей, что обеспечивает яркое и четкое изображение.</p>\n\n<p>Внутри смартфона установлен процессор MediaTek Helio G88 с частотой 1,8 ГГц, что позволяет использовать приложения и игры требующие высокой производительности. Большой объем оперативной памяти 8 ГБ и встроенной памяти 128 ГБ позволяет хранить большое количество фотографий, видео, музыки и других файлов.</p>\n\n<p>Смартфон Infinix HOT 30 оснащен камерой с разрешением 50 + 0.3 + TOF. Фронтальная камера имеет разрешение 8 Мп, что позволяет делать качественные селфи.</p>\n\n<p>Среди дополнительных функций смартфона - сканер отпечатка пальца, поддержка двух SIM-карт и аккумулятор емкостью 5000 мАч, который обеспечивает длительное автономное использование устройства.</p>\n\n<p>Самый крупный объем памяти на рынке, мощный процессор и высококачественная тройная камера делают Infinix HOT 30 8/128Gb отличным выбором для тех, кто ищет мощный и функциональный смартфон по доступной цене.</p>\n',
    frontName: 'Смартфон Infinix HOT 30 8/128Gb Surfing Green',
    slug: 'infinix-hot-30-8-128gb-surfing-green',
    brand: 'Infinix',
    catalogId: {
      productId: 'prod6670096',
      skuId: 'sku5990106',
      serialId: null,
    },
    colors: [
      {
        id: 'spec5900010',
        name: 'зеленый',
        code: '#4de4aa',
        catalogIdData: {
          productId: 'prod6670096',
          skuId: 'sku5990106',
          serialId: null,
        },
        skuSlug: 'infinix-hot-30-8-128gb-surfing-green',
      },
      {
        id: 'spec400001',
        name: 'белый',
        code: '#FFFFFF',
        catalogIdData: {
          productId: 'prod6670096',
          skuId: 'sku5990107',
          serialId: null,
        },
        skuSlug: 'infinix-hot-30-8-128gb-sonic-white',
      },
      {
        id: 'spec300007',
        name: 'черный',
        code: '#000000',
        catalogIdData: {
          productId: 'prod6670096',
          skuId: 'sku5990105',
          serialId: null,
        },
        skuSlug: 'infinix-hot-30-8-128gb-racing-black',
      },
    ],
    images: [
      {
        url: '/api/media/asset?mediaId=m6170127',
        main: true,
        path: 'https://msk.tele2.ru/api/media/asset?mediaId=m6170127',
      },
      {
        url: '/api/media/asset?mediaId=m6170128',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6170128',
      },
      {
        url: '/api/media/asset?mediaId=m6170129',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6170129',
      },
      {
        url: '/api/media/asset?mediaId=m6170130',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6170130',
      },
      {
        url: '/api/media/asset?mediaId=m6170131',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6170131',
      },
    ],
    price: {
      amount: 12990,
      currency: 'RUB',
    },
    salePrice: null,
    discountValue: null,
    url: null,
    barcode: null,
    eventMessage: {
      id: '1400001',
      name: 'Новинка',
      type: 'new',
      iconColor: null,
      icon: 'https://msk.tele2.ru/api/media/asset?mediaId=m4940001',
      description: null,
    },
    categorySlug: 'smartphones',
    promo: true,
    promoCampaigns: [
      {
        id: '2000002',
        externalId: '158',
        name: 'Скидка на смартфоны 500',
        slug: 'smartphones',
        promoTextNotAuth: '500 ₽ скидка – 500 минут ',
        promoPageLink: 'https://msk.tele2.ru/minutes-management/smartphones',
        promoText: '500 ₽ скидка – 250 минут ',
        infoBlockTitle: 'Скидка до 500 ₽ за минуты',
        infoBlockText: 'Скидка за минуты',
        infoBlockIcon: null,
        priority: 100,
        displayType: 'combined',
        labelText: 'Скидка до 500 ₽ за минуты',
        labelTextColor: '#C882FF',
        labelBackgroundColor: '#F4E5FF',
        tooltipText: 'Обменяй минуты на скидку на устройства.',
      },
      {
        id: '1400002',
        externalId: '15',
        name: 'Комбо 1.0 (-50%)',
        slug: null,
        promoTextNotAuth: 'при покупке комбо 3 в 1',
        promoPageLink: 'https://msk.tele2.ru/promotions/article/discount-infinix-smartphones/discount-infinix-smartphones',
        promoText: null,
        infoBlockTitle: 'Скидка за комплект',
        infoBlockText: 'При покупке смартфона, SIM-карты и страховки',
        infoBlockIcon: 'https://s3.tele2.ru/ds-site/images/shop/combo/50-sale-bage.svg',
        priority: 360,
        displayType: 'text',
        labelText: null,
        labelTextColor: null,
        labelBackgroundColor: null,
        tooltipText: null,
      },
    ],
    saleVariants: [
      {
        catalogId: {
          productId: 'prod6820001',
          skuId: 'sku6140006',
          serialId: null,
        },
        skuType: 'comboSku',
        promoCampaigns: [
          {
            id: '1400002',
            externalId: '15',
            name: 'Комбо 1.0 (-50%)',
            slug: null,
            promoTextNotAuth: 'при покупке комбо 3 в 1',
            promoPageLink: 'https://msk.tele2.ru/promotions/article/discount-infinix-smartphones/discount-infinix-smartphones',
            promoText: null,
            infoBlockTitle: 'Скидка за комплект',
            infoBlockText: 'При покупке смартфона, SIM-карты и страховки',
            infoBlockIcon: 'https://s3.tele2.ru/ds-site/images/shop/combo/50-sale-bage.svg',
            priority: 360,
            displayType: 'text',
            labelText: null,
            labelTextColor: null,
            labelBackgroundColor: null,
            tooltipText: null,
          },
        ],
        salePrice: null,
      },
    ],
  },
  {
    article: '0100-494385',
    pickupAvailable: true,
    deliveryAvailable: false,
    description: null,
    frontName: 'Смартфон Infinix NOTE 30i 8/128Gb Impression Green',
    slug: 'infinix-note-30i-8-128gb-impression-green',
    brand: 'Infinix',
    catalogId: {
      productId: 'prod6780036',
      skuId: 'sku6130600',
      serialId: null,
    },
    colors: [
      {
        id: 'spec5900009',
        name: 'желтый',
        code: '#ffe681',
        catalogIdData: {
          productId: 'prod6780036',
          skuId: 'sku6100034',
          serialId: null,
        },
        skuSlug: 'infinix-note-30i-8-128gb-variable-gold',
      },
      {
        id: 'spec300007',
        name: 'черный',
        code: '#000000',
        catalogIdData: {
          productId: 'prod6780036',
          skuId: 'sku6100033',
          serialId: null,
        },
        skuSlug: 'infinix-note-30i-8-128gb-obsidian-black',
      },
      {
        id: 'spec5900010',
        name: 'зеленый',
        code: '#4de4aa',
        catalogIdData: {
          productId: 'prod6780036',
          skuId: 'sku6130600',
          serialId: null,
        },
        skuSlug: 'infinix-note-30i-8-128gb-impression-green',
      },
    ],
    images: [
      {
        url: '/api/media/asset?mediaId=m6140011',
        main: true,
        path: 'https://msk.tele2.ru/api/media/asset?mediaId=m6140011',
      },
      {
        url: '/api/media/asset?mediaId=m6140012',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6140012',
      },
      {
        url: '/api/media/asset?mediaId=m6140013',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6140013',
      },
      {
        url: '/api/media/asset?mediaId=m6140015',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6140015',
      },
      {
        url: '/api/media/asset?mediaId=m6140014',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6140014',
      },
    ],
    price: {
      amount: 14990,
      currency: 'RUB',
    },
    salePrice: null,
    discountValue: null,
    url: null,
    barcode: null,
    eventMessage: {
      id: '1400001',
      name: 'Новинка',
      type: 'new',
      iconColor: null,
      icon: 'https://msk.tele2.ru/api/media/asset?mediaId=m4940001',
      description: null,
    },
    categorySlug: 'smartphones',
    promo: true,
    promoCampaigns: [
      {
        id: '1400002',
        externalId: '15',
        name: 'Комбо 1.0 (-50%)',
        slug: null,
        promoTextNotAuth: 'при покупке комбо 3 в 1',
        promoPageLink: 'https://msk.tele2.ru/promotions/article/discount-infinix-smartphones/discount-infinix-smartphones',
        promoText: null,
        infoBlockTitle: 'Скидка за комплект',
        infoBlockText: 'При покупке смартфона, SIM-карты и страховки',
        infoBlockIcon: 'https://s3.tele2.ru/ds-site/images/shop/combo/50-sale-bage.svg',
        priority: 360,
        displayType: 'text',
        labelText: null,
        labelTextColor: null,
        labelBackgroundColor: null,
        tooltipText: null,
      },
      {
        id: '1400003',
        externalId: '160',
        name: 'Скидка на смартфоны 1000',
        slug: 'smartphones',
        promoTextNotAuth: '1000 ₽ скидка – 1000 минут ',
        promoPageLink: 'https://msk.tele2.ru/minutes-management/smartphones',
        promoText: '1000 ₽ скидка – 500 минут ',
        infoBlockTitle: 'Скидка до 1000 ₽ за минуты',
        infoBlockText: 'Скидка за минуты',
        infoBlockIcon: null,
        priority: 120,
        displayType: 'combined',
        labelText: 'Скидка до 1000 ₽ за минуты',
        labelTextColor: '#C882FF',
        labelBackgroundColor: '#F4E5FF',
        tooltipText: 'Обменяй минуты на скидку на устройства.',
      },
      {
        id: '2000002',
        externalId: '158',
        name: 'Скидка на смартфоны 500',
        slug: 'smartphones',
        promoTextNotAuth: '500 ₽ скидка – 500 минут ',
        promoPageLink: 'https://msk.tele2.ru/minutes-management/smartphones',
        promoText: '500 ₽ скидка – 250 минут ',
        infoBlockTitle: 'Скидка до 500 ₽ за минуты',
        infoBlockText: 'Скидка за минуты',
        infoBlockIcon: null,
        priority: 100,
        displayType: 'combined',
        labelText: 'Скидка до 500 ₽ за минуты',
        labelTextColor: '#C882FF',
        labelBackgroundColor: '#F4E5FF',
        tooltipText: 'Обменяй минуты на скидку на устройства.',
      },
      {
        id: '1400005',
        externalId: '162',
        name: 'Скидка на смартфоны 2000',
        slug: 'smartphones',
        promoTextNotAuth: '2000 ₽ скидка – 2000 минут ',
        promoPageLink: 'https://msk.tele2.ru/minutes-management/smartphones',
        promoText: '2000 ₽ скидка – 1000 минут ',
        infoBlockTitle: 'Скидка до 2000 ₽ за минуты',
        infoBlockText: 'Скидка за минуты',
        infoBlockIcon: null,
        priority: 140,
        displayType: 'combined',
        labelText: 'Скидка до 2000 ₽ за минуты',
        labelTextColor: '#C882FF',
        labelBackgroundColor: '#F4E5FF',
        tooltipText: 'Обменяй минуты на скидку на устройства.',
      },
      {
        id: '2500002',
        externalId: '161',
        name: 'Скидка на смартфоны 1500',
        slug: 'smartphones',
        promoTextNotAuth: '1500 ₽ скидка – 1500 минут ',
        promoPageLink: 'https://msk.tele2.ru/minutes-management/smartphones',
        promoText: '1500 ₽ скидка – 750 минут ',
        infoBlockTitle: 'Скидка до 1500 ₽ за минуты',
        infoBlockText: 'Скидка за минуты',
        infoBlockIcon: null,
        priority: 130,
        displayType: 'combined',
        labelText: 'Скидка до 1000 ₽ за минуты',
        labelTextColor: '#C882FF',
        labelBackgroundColor: '#F4E5FF',
        tooltipText: 'Обменяй минуты на скидку на устройства.',
      },
    ],
    saleVariants: [
      {
        catalogId: {
          productId: 'prod6820001',
          skuId: 'sku6140006',
          serialId: null,
        },
        skuType: 'comboSku',
        promoCampaigns: [
          {
            id: '1400002',
            externalId: '15',
            name: 'Комбо 1.0 (-50%)',
            slug: null,
            promoTextNotAuth: 'при покупке комбо 3 в 1',
            promoPageLink: 'https://msk.tele2.ru/promotions/article/discount-infinix-smartphones/discount-infinix-smartphones',
            promoText: null,
            infoBlockTitle: 'Скидка за комплект',
            infoBlockText: 'При покупке смартфона, SIM-карты и страховки',
            infoBlockIcon: 'https://s3.tele2.ru/ds-site/images/shop/combo/50-sale-bage.svg',
            priority: 360,
            displayType: 'text',
            labelText: null,
            labelTextColor: null,
            labelBackgroundColor: null,
            tooltipText: null,
          },
        ],
        salePrice: null,
      },
    ],
  },
  {
    article: '0100-492971',
    pickupAvailable: false,
    deliveryAvailable: true,
    description: null,
    frontName: 'Смартфон Infinix NOTE 30i 8/256Gb Obsidian Black',
    slug: 'infinix-note-30i-8-256gb-obsidian-black',
    brand: 'Infinix',
    catalogId: {
      productId: 'prod6750002',
      skuId: 'sku6070003',
      serialId: null,
    },
    colors: [
      {
        id: 'spec300007',
        name: 'черный',
        code: '#000000',
        catalogIdData: {
          productId: 'prod6750002',
          skuId: 'sku6070003',
          serialId: null,
        },
        skuSlug: 'infinix-note-30i-8-256gb-obsidian-black',
      },
      {
        id: 'spec1200001',
        name: 'золотой',
        code: '#FFE4B5',
        catalogIdData: {
          productId: 'prod6750002',
          skuId: 'sku6070004',
          serialId: null,
        },
        skuSlug: 'infinix-note-30i-8-256gb-variable-gold',
      },
      {
        id: 'spec5900010',
        name: 'зеленый',
        code: '#4de4aa',
        catalogIdData: {
          productId: 'prod6750002',
          skuId: 'sku6130601',
          serialId: null,
        },
        skuSlug: 'infinix-note-30i-8-256gb-impression-green',
      },
    ],
    images: [
      {
        url: '/api/media/asset?mediaId=m6090009',
        main: true,
        path: 'https://msk.tele2.ru/api/media/asset?mediaId=m6090009',
      },
      {
        url: '/api/media/asset?mediaId=m6090010',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6090010',
      },
      {
        url: '/api/media/asset?mediaId=m6090011',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6090011',
      },
      {
        url: '/api/media/asset?mediaId=m6090013',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6090013',
      },
      {
        url: '/api/media/asset?mediaId=m6090012',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6090012',
      },
    ],
    price: {
      amount: 15790,
      currency: 'RUB',
    },
    salePrice: null,
    discountValue: null,
    url: null,
    barcode: null,
    eventMessage: {
      id: '1400001',
      name: 'Новинка',
      type: 'new',
      iconColor: null,
      icon: 'https://msk.tele2.ru/api/media/asset?mediaId=m4940001',
      description: null,
    },
    categorySlug: 'smartphones',
    promo: true,
    promoCampaigns: [
      {
        id: '1400002',
        externalId: '15',
        name: 'Комбо 1.0 (-50%)',
        slug: null,
        promoTextNotAuth: 'при покупке комбо 3 в 1',
        promoPageLink: 'https://msk.tele2.ru/promotions/article/discount-infinix-smartphones/discount-infinix-smartphones',
        promoText: null,
        infoBlockTitle: 'Скидка за комплект',
        infoBlockText: 'При покупке смартфона, SIM-карты и страховки',
        infoBlockIcon: 'https://s3.tele2.ru/ds-site/images/shop/combo/50-sale-bage.svg',
        priority: 360,
        displayType: 'text',
        labelText: null,
        labelTextColor: null,
        labelBackgroundColor: null,
        tooltipText: null,
      },
      {
        id: '1400003',
        externalId: '160',
        name: 'Скидка на смартфоны 1000',
        slug: 'smartphones',
        promoTextNotAuth: '1000 ₽ скидка – 1000 минут ',
        promoPageLink: 'https://msk.tele2.ru/minutes-management/smartphones',
        promoText: '1000 ₽ скидка – 500 минут ',
        infoBlockTitle: 'Скидка до 1000 ₽ за минуты',
        infoBlockText: 'Скидка за минуты',
        infoBlockIcon: null,
        priority: 120,
        displayType: 'combined',
        labelText: 'Скидка до 1000 ₽ за минуты',
        labelTextColor: '#C882FF',
        labelBackgroundColor: '#F4E5FF',
        tooltipText: 'Обменяй минуты на скидку на устройства.',
      },
      {
        id: '2000002',
        externalId: '158',
        name: 'Скидка на смартфоны 500',
        slug: 'smartphones',
        promoTextNotAuth: '500 ₽ скидка – 500 минут ',
        promoPageLink: 'https://msk.tele2.ru/minutes-management/smartphones',
        promoText: '500 ₽ скидка – 250 минут ',
        infoBlockTitle: 'Скидка до 500 ₽ за минуты',
        infoBlockText: 'Скидка за минуты',
        infoBlockIcon: null,
        priority: 100,
        displayType: 'combined',
        labelText: 'Скидка до 500 ₽ за минуты',
        labelTextColor: '#C882FF',
        labelBackgroundColor: '#F4E5FF',
        tooltipText: 'Обменяй минуты на скидку на устройства.',
      },
      {
        id: '1400005',
        externalId: '162',
        name: 'Скидка на смартфоны 2000',
        slug: 'smartphones',
        promoTextNotAuth: '2000 ₽ скидка – 2000 минут ',
        promoPageLink: 'https://msk.tele2.ru/minutes-management/smartphones',
        promoText: '2000 ₽ скидка – 1000 минут ',
        infoBlockTitle: 'Скидка до 2000 ₽ за минуты',
        infoBlockText: 'Скидка за минуты',
        infoBlockIcon: null,
        priority: 140,
        displayType: 'combined',
        labelText: 'Скидка до 2000 ₽ за минуты',
        labelTextColor: '#C882FF',
        labelBackgroundColor: '#F4E5FF',
        tooltipText: 'Обменяй минуты на скидку на устройства.',
      },
      {
        id: '1400006',
        externalId: '163',
        name: 'Скидка на смартфоны 3000',
        slug: 'smartphones',
        promoTextNotAuth: '3000 ₽ скидка – 3000 минут ',
        promoPageLink: 'https://msk.tele2.ru/minutes-management/smartphones',
        promoText: '3000 ₽ скидка – 1500 минут ',
        infoBlockTitle: 'Скидка до 3000 ₽ за минуты',
        infoBlockText: 'Скидка за минуты',
        infoBlockIcon: null,
        priority: 150,
        displayType: 'combined',
        labelText: 'Скидка до 3000 ₽ за минуты',
        labelTextColor: '#C882FF',
        labelBackgroundColor: '#F4E5FF',
        tooltipText: 'Обменяй минуты на скидку на устройства.',
      },
      {
        id: '2500002',
        externalId: '161',
        name: 'Скидка на смартфоны 1500',
        slug: 'smartphones',
        promoTextNotAuth: '1500 ₽ скидка – 1500 минут ',
        promoPageLink: 'https://msk.tele2.ru/minutes-management/smartphones',
        promoText: '1500 ₽ скидка – 750 минут ',
        infoBlockTitle: 'Скидка до 1500 ₽ за минуты',
        infoBlockText: 'Скидка за минуты',
        infoBlockIcon: null,
        priority: 130,
        displayType: 'combined',
        labelText: 'Скидка до 1000 ₽ за минуты',
        labelTextColor: '#C882FF',
        labelBackgroundColor: '#F4E5FF',
        tooltipText: 'Обменяй минуты на скидку на устройства.',
      },
    ],
    saleVariants: [
      {
        catalogId: {
          productId: 'prod6820001',
          skuId: 'sku6140006',
          serialId: null,
        },
        skuType: 'comboSku',
        promoCampaigns: [
          {
            id: '1400002',
            externalId: '15',
            name: 'Комбо 1.0 (-50%)',
            slug: null,
            promoTextNotAuth: 'при покупке комбо 3 в 1',
            promoPageLink: 'https://msk.tele2.ru/promotions/article/discount-infinix-smartphones/discount-infinix-smartphones',
            promoText: null,
            infoBlockTitle: 'Скидка за комплект',
            infoBlockText: 'При покупке смартфона, SIM-карты и страховки',
            infoBlockIcon: 'https://s3.tele2.ru/ds-site/images/shop/combo/50-sale-bage.svg',
            priority: 360,
            displayType: 'text',
            labelText: null,
            labelTextColor: null,
            labelBackgroundColor: null,
            tooltipText: null,
          },
        ],
        salePrice: null,
      },
    ],
  },
  {
    article: '0100-492963',
    pickupAvailable: true,
    deliveryAvailable: false,
    description: '<p>Infinix NOTE 30 ― первый смартфон серии NOTE, имеющий стеклянный корпус. При этом корпус обладает высокой прочностью и соответствует стандартам защиты от пыли IP5X и брызг IPX3, обеспечивает надежную защиту электронной начинки от механических повреждений и влаги.</p>\n\n<p>Infinix NOTE 30 с поддержкой NFC работает на базе 6-нм микропроцессора MediaTek Helio G99, который вместе с 8 ГБ оперативной памяти отвечает за производительность и быстродействие. Запатентованная технология UPS повышает качество сигнала при просмотре видеоконтента или во время игры, а также усиливает сигнал Wi-Fi, позволяя все время оставаться на связи. Дисплей диагональю 6.78 дюймов обновляется с частотой 120 Гц. В сочетании с технологией Magellan Engine 1.1 он позволяет максимально плавно отображать контент на экране, а при активации специального режима можно снизить интенсивность синего спектра, из-за которого устают глаза. В таком режиме можно комфортно играть, смотреть сериалы или читать еще дольше без вреда для зрения.</p>\n\n<p>Смартфон оснащен тройной камерой выдающей четкие снимки. Режим «Супер Ночь» автоматически адаптируется к условиям освещенности для получения детализированных и ярких снимков. Есть у смартфона и отдельный фильтр для уличной фотографии, а в режиме съемки «Двойное видео» можно записывать ролики сразу на основную и фронтальную камеры.</p>\n\n<p>За звук смартфона отвечают стереодинамики. С их помощью смартфон воспроизводит звук профессионального качества с насыщенными басами и чистыми высокими частотами.</p>\n\n<p>Быстрая зарядка мощностью 45 Вт позволяет зарядить смартфон на 75% всего за полчаса. Аккумулятор емкостью 5000 мА*ч рассчитан на 1000 циклов перезарядки без потери исходных параметров. К тому же сам смартфон может выступать в качестве пауэрбанка для прочих гаджетов: от него можно заряжать другие смартфоны, смарт-часы или наушники. При активном использовании телефон может работать напрямую от зарядного устройства в обход батареи - так снижается ее нагрев и, соответственно, вероятность преждевременного выхода смартфона из строя.</p>\n',
    frontName: 'Смартфон Infinix NOTE 30 8/256Gb Interstellar Blue',
    slug: 'infinix-note-30-8-256gb-interstellar-blue',
    brand: 'Infinix',
    catalogId: {
      productId: 'prod6750001',
      skuId: 'sku6070002',
      serialId: null,
    },
    colors: [
      {
        id: 'spec300007',
        name: 'черный',
        code: '#000000',
        catalogIdData: {
          productId: 'prod6750001',
          skuId: 'sku6070001',
          serialId: null,
        },
        skuSlug: 'infinix-note-30-8-256gb-obsidian-black',
      },
      {
        id: 'spec6100008',
        name: 'голубой',
        code: '#abf1fd',
        catalogIdData: {
          productId: 'prod6750001',
          skuId: 'sku6070002',
          serialId: null,
        },
        skuSlug: 'infinix-note-30-8-256gb-interstellar-blue',
      },
      {
        id: 'spec5900009',
        name: 'желтый',
        code: '#ffe681',
        catalogIdData: {
          productId: 'prod6750001',
          skuId: 'sku6130596',
          serialId: null,
        },
        skuSlug: 'infinix-note-30-8-256gb-sunset-gold',
      },
    ],
    images: [
      {
        url: '/api/media/asset?mediaId=m6020028',
        main: true,
        path: 'https://msk.tele2.ru/api/media/asset?mediaId=m6020028',
      },
      {
        url: '/api/media/asset?mediaId=m6020031',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6020031',
      },
      {
        url: '/api/media/asset?mediaId=m6020030',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6020030',
      },
      {
        url: '/api/media/asset?mediaId=m6020029',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6020029',
      },
    ],
    price: {
      amount: 16990,
      currency: 'RUB',
    },
    salePrice: null,
    discountValue: null,
    url: null,
    barcode: null,
    eventMessage: {
      id: '1400001',
      name: 'Новинка',
      type: 'new',
      iconColor: null,
      icon: 'https://msk.tele2.ru/api/media/asset?mediaId=m4940001',
      description: null,
    },
    categorySlug: 'smartphones',
    promo: true,
    promoCampaigns: [
      {
        id: '2000002',
        externalId: '158',
        name: 'Скидка на смартфоны 500',
        slug: 'smartphones',
        promoTextNotAuth: '500 ₽ скидка – 500 минут ',
        promoPageLink: 'https://msk.tele2.ru/minutes-management/smartphones',
        promoText: '500 ₽ скидка – 250 минут ',
        infoBlockTitle: 'Скидка до 500 ₽ за минуты',
        infoBlockText: 'Скидка за минуты',
        infoBlockIcon: null,
        priority: 100,
        displayType: 'combined',
        labelText: 'Скидка до 500 ₽ за минуты',
        labelTextColor: '#C882FF',
        labelBackgroundColor: '#F4E5FF',
        tooltipText: 'Обменяй минуты на скидку на устройства.',
      },
      {
        id: '1400005',
        externalId: '162',
        name: 'Скидка на смартфоны 2000',
        slug: 'smartphones',
        promoTextNotAuth: '2000 ₽ скидка – 2000 минут ',
        promoPageLink: 'https://msk.tele2.ru/minutes-management/smartphones',
        promoText: '2000 ₽ скидка – 1000 минут ',
        infoBlockTitle: 'Скидка до 2000 ₽ за минуты',
        infoBlockText: 'Скидка за минуты',
        infoBlockIcon: null,
        priority: 140,
        displayType: 'combined',
        labelText: 'Скидка до 2000 ₽ за минуты',
        labelTextColor: '#C882FF',
        labelBackgroundColor: '#F4E5FF',
        tooltipText: 'Обменяй минуты на скидку на устройства.',
      },
      {
        id: '1400006',
        externalId: '163',
        name: 'Скидка на смартфоны 3000',
        slug: 'smartphones',
        promoTextNotAuth: '3000 ₽ скидка – 3000 минут ',
        promoPageLink: 'https://msk.tele2.ru/minutes-management/smartphones',
        promoText: '3000 ₽ скидка – 1500 минут ',
        infoBlockTitle: 'Скидка до 3000 ₽ за минуты',
        infoBlockText: 'Скидка за минуты',
        infoBlockIcon: null,
        priority: 150,
        displayType: 'combined',
        labelText: 'Скидка до 3000 ₽ за минуты',
        labelTextColor: '#C882FF',
        labelBackgroundColor: '#F4E5FF',
        tooltipText: 'Обменяй минуты на скидку на устройства.',
      },
      {
        id: '1400007',
        externalId: '164',
        name: 'Скидка на смартфоны 4000',
        slug: 'smartphones',
        promoTextNotAuth: '4000 ₽ скидка – 4000 минут ',
        promoPageLink: 'https://msk.tele2.ru/minutes-management/smartphones',
        promoText: '4000 ₽ скидка – 2000 минут ',
        infoBlockTitle: 'Скидка до 4000 ₽ за минуты',
        infoBlockText: 'Скидка за минуты',
        infoBlockIcon: null,
        priority: 160,
        displayType: 'combined',
        labelText: 'Скидка до 4000 ₽ за минуты',
        labelTextColor: '#C882FF',
        labelBackgroundColor: '#F4E5FF',
        tooltipText: 'Обменяй минуты на скидку на устройства.',
      },
      {
        id: '1400002',
        externalId: '15',
        name: 'Комбо 1.0 (-50%)',
        slug: null,
        promoTextNotAuth: 'при покупке комбо 3 в 1',
        promoPageLink: 'https://msk.tele2.ru/promotions/article/discount-infinix-smartphones/discount-infinix-smartphones',
        promoText: null,
        infoBlockTitle: 'Скидка за комплект',
        infoBlockText: 'При покупке смартфона, SIM-карты и страховки',
        infoBlockIcon: 'https://s3.tele2.ru/ds-site/images/shop/combo/50-sale-bage.svg',
        priority: 360,
        displayType: 'text',
        labelText: null,
        labelTextColor: null,
        labelBackgroundColor: null,
        tooltipText: null,
      },
      {
        id: '1400003',
        externalId: '160',
        name: 'Скидка на смартфоны 1000',
        slug: 'smartphones',
        promoTextNotAuth: '1000 ₽ скидка – 1000 минут ',
        promoPageLink: 'https://msk.tele2.ru/minutes-management/smartphones',
        promoText: '1000 ₽ скидка – 500 минут ',
        infoBlockTitle: 'Скидка до 1000 ₽ за минуты',
        infoBlockText: 'Скидка за минуты',
        infoBlockIcon: null,
        priority: 120,
        displayType: 'combined',
        labelText: 'Скидка до 1000 ₽ за минуты',
        labelTextColor: '#C882FF',
        labelBackgroundColor: '#F4E5FF',
        tooltipText: 'Обменяй минуты на скидку на устройства.',
      },
      {
        id: '2500002',
        externalId: '161',
        name: 'Скидка на смартфоны 1500',
        slug: 'smartphones',
        promoTextNotAuth: '1500 ₽ скидка – 1500 минут ',
        promoPageLink: 'https://msk.tele2.ru/minutes-management/smartphones',
        promoText: '1500 ₽ скидка – 750 минут ',
        infoBlockTitle: 'Скидка до 1500 ₽ за минуты',
        infoBlockText: 'Скидка за минуты',
        infoBlockIcon: null,
        priority: 130,
        displayType: 'combined',
        labelText: 'Скидка до 1000 ₽ за минуты',
        labelTextColor: '#C882FF',
        labelBackgroundColor: '#F4E5FF',
        tooltipText: 'Обменяй минуты на скидку на устройства.',
      },
    ],
    saleVariants: [
      {
        catalogId: {
          productId: 'prod6820001',
          skuId: 'sku6140006',
          serialId: null,
        },
        skuType: 'comboSku',
        promoCampaigns: [
          {
            id: '1400002',
            externalId: '15',
            name: 'Комбо 1.0 (-50%)',
            slug: null,
            promoTextNotAuth: 'при покупке комбо 3 в 1',
            promoPageLink: 'https://msk.tele2.ru/promotions/article/discount-infinix-smartphones/discount-infinix-smartphones',
            promoText: null,
            infoBlockTitle: 'Скидка за комплект',
            infoBlockText: 'При покупке смартфона, SIM-карты и страховки',
            infoBlockIcon: 'https://s3.tele2.ru/ds-site/images/shop/combo/50-sale-bage.svg',
            priority: 360,
            displayType: 'text',
            labelText: null,
            labelTextColor: null,
            labelBackgroundColor: null,
            tooltipText: null,
          },
        ],
        salePrice: null,
      },
    ],
  },
  {
    article: '0100-498341',
    pickupAvailable: true,
    deliveryAvailable: true,
    description: null,
    frontName: 'Смартфон Infinix HOT 40 8/256Gb Starlit Black',
    slug: 'infinix-hot-40-8-256gb-starlit-black',
    brand: 'Infinix',
    catalogId: {
      productId: 'prod7220032',
      skuId: 'sku6490034',
      serialId: null,
    },
    colors: [
      {
        id: 'spec5900010',
        name: 'зеленый',
        code: '#4de4aa',
        catalogIdData: {
          productId: 'prod7220032',
          skuId: 'sku6610002',
          serialId: null,
        },
        skuSlug: 'infinix-hot-40-8-256gb-starfall-green',
      },
      {
        id: 'spec300007',
        name: 'черный',
        code: '#000000',
        catalogIdData: {
          productId: 'prod7220032',
          skuId: 'sku6490034',
          serialId: null,
        },
        skuSlug: 'infinix-hot-40-8-256gb-starlit-black',
      },
      {
        id: 'spec6100008',
        name: 'голубой',
        code: '#abf1fd',
        catalogIdData: {
          productId: 'prod7220032',
          skuId: 'sku6490033',
          serialId: null,
        },
        skuSlug: 'infinix-hot-40-8-256gb-palm-blue',
      },
      {
        id: 'spec1200001',
        name: 'золотой',
        code: '#FFE4B5',
        catalogIdData: {
          productId: 'prod7220032',
          skuId: 'sku6490032',
          serialId: null,
        },
        skuSlug: 'infinix-hot-40-8-256gb-horizon-gold',
      },
    ],
    images: [
      {
        url: '/api/media/asset?mediaId=m6590023',
        main: true,
        path: 'https://msk.tele2.ru/api/media/asset?mediaId=m6590023',
      },
      {
        url: '/api/media/asset?mediaId=m6590024',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6590024',
      },
      {
        url: '/api/media/asset?mediaId=m6590025',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6590025',
      },
      {
        url: '/api/media/asset?mediaId=m6590026',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6590026',
      },
      {
        url: '/api/media/asset?mediaId=m6590027',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6590027',
      },
    ],
    price: {
      amount: 15990,
      currency: 'RUB',
    },
    salePrice: null,
    discountValue: null,
    url: null,
    barcode: null,
    eventMessage: {
      id: '1400001',
      name: 'Новинка',
      type: 'new',
      iconColor: null,
      icon: 'https://msk.tele2.ru/api/media/asset?mediaId=m4940001',
      description: null,
    },
    categorySlug: 'smartphones',
    promo: true,
    promoCampaigns: [
      {
        id: '1400002',
        externalId: '15',
        name: 'Комбо 1.0 (-50%)',
        slug: null,
        promoTextNotAuth: 'при покупке комбо 3 в 1',
        promoPageLink: 'https://msk.tele2.ru/promotions/article/discount-infinix-smartphones/discount-infinix-smartphones',
        promoText: null,
        infoBlockTitle: 'Скидка за комплект',
        infoBlockText: 'При покупке смартфона, SIM-карты и страховки',
        infoBlockIcon: 'https://s3.tele2.ru/ds-site/images/shop/combo/50-sale-bage.svg',
        priority: 360,
        displayType: 'text',
        labelText: null,
        labelTextColor: null,
        labelBackgroundColor: null,
        tooltipText: null,
      },
    ],
    saleVariants: [
      {
        catalogId: {
          productId: 'prod6820001',
          skuId: 'sku6140006',
          serialId: null,
        },
        skuType: 'comboSku',
        promoCampaigns: [
          {
            id: '1400002',
            externalId: '15',
            name: 'Комбо 1.0 (-50%)',
            slug: null,
            promoTextNotAuth: 'при покупке комбо 3 в 1',
            promoPageLink: 'https://msk.tele2.ru/promotions/article/discount-infinix-smartphones/discount-infinix-smartphones',
            promoText: null,
            infoBlockTitle: 'Скидка за комплект',
            infoBlockText: 'При покупке смартфона, SIM-карты и страховки',
            infoBlockIcon: 'https://s3.tele2.ru/ds-site/images/shop/combo/50-sale-bage.svg',
            priority: 360,
            displayType: 'text',
            labelText: null,
            labelTextColor: null,
            labelBackgroundColor: null,
            tooltipText: null,
          },
        ],
        salePrice: null,
      },
    ],
  },
  {
    article: '0100-498382',
    pickupAvailable: false,
    deliveryAvailable: false,
    description: null,
    frontName: 'Смартфон Infinix HOT 40i 8/256Gb Horizon Gold',
    slug: 'infinix-hot-40i-8-256gb-horizon-gold',
    brand: 'Infinix',
    catalogId: {
      productId: 'prod7220035',
      skuId: 'sku6490041',
      serialId: null,
    },
    colors: [
      {
        id: 'spec300007',
        name: 'черный',
        code: '#000000',
        catalogIdData: {
          productId: 'prod7220035',
          skuId: 'sku6490043',
          serialId: null,
        },
        skuSlug: 'infinix-hot-40i-8-256gb-starlit-black',
      },
      {
        id: 'spec1200001',
        name: 'золотой',
        code: '#FFE4B5',
        catalogIdData: {
          productId: 'prod7220035',
          skuId: 'sku6490041',
          serialId: null,
        },
        skuSlug: 'infinix-hot-40i-8-256gb-horizon-gold',
      },
      {
        id: 'spec6100008',
        name: 'голубой',
        code: '#abf1fd',
        catalogIdData: {
          productId: 'prod7220035',
          skuId: 'sku6490042',
          serialId: null,
        },
        skuSlug: 'infinix-hot-40i-8-256gb-palm-blue',
      },
    ],
    images: [
      {
        url: '/api/media/asset?mediaId=m6590028',
        main: true,
        path: 'https://msk.tele2.ru/api/media/asset?mediaId=m6590028',
      },
      {
        url: '/api/media/asset?mediaId=m6590029',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6590029',
      },
      {
        url: '/api/media/asset?mediaId=m6590030',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6590030',
      },
      {
        url: '/api/media/asset?mediaId=m6590031',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6590031',
      },
      {
        url: '/api/media/asset?mediaId=m6590032',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6590032',
      },
    ],
    price: {
      amount: 12990,
      currency: 'RUB',
    },
    salePrice: null,
    discountValue: null,
    url: null,
    barcode: null,
    eventMessage: {
      id: '1400001',
      name: 'Новинка',
      type: 'new',
      iconColor: null,
      icon: 'https://msk.tele2.ru/api/media/asset?mediaId=m4940001',
      description: null,
    },
    categorySlug: 'smartphones',
    promo: true,
    promoCampaigns: [
      {
        id: '1400002',
        externalId: '15',
        name: 'Комбо 1.0 (-50%)',
        slug: null,
        promoTextNotAuth: 'при покупке комбо 3 в 1',
        promoPageLink: 'https://msk.tele2.ru/promotions/article/discount-infinix-smartphones/discount-infinix-smartphones',
        promoText: null,
        infoBlockTitle: 'Скидка за комплект',
        infoBlockText: 'При покупке смартфона, SIM-карты и страховки',
        infoBlockIcon: 'https://s3.tele2.ru/ds-site/images/shop/combo/50-sale-bage.svg',
        priority: 360,
        displayType: 'text',
        labelText: null,
        labelTextColor: null,
        labelBackgroundColor: null,
        tooltipText: null,
      },
    ],
    saleVariants: [
      {
        catalogId: {
          productId: 'prod6820001',
          skuId: 'sku6140006',
          serialId: null,
        },
        skuType: 'comboSku',
        promoCampaigns: [
          {
            id: '1400002',
            externalId: '15',
            name: 'Комбо 1.0 (-50%)',
            slug: null,
            promoTextNotAuth: 'при покупке комбо 3 в 1',
            promoPageLink: 'https://msk.tele2.ru/promotions/article/discount-infinix-smartphones/discount-infinix-smartphones',
            promoText: null,
            infoBlockTitle: 'Скидка за комплект',
            infoBlockText: 'При покупке смартфона, SIM-карты и страховки',
            infoBlockIcon: 'https://s3.tele2.ru/ds-site/images/shop/combo/50-sale-bage.svg',
            priority: 360,
            displayType: 'text',
            labelText: null,
            labelTextColor: null,
            labelBackgroundColor: null,
            tooltipText: null,
          },
        ],
        salePrice: null,
      },
    ],
  },
  {
    article: '0100-498564',
    pickupAvailable: false,
    deliveryAvailable: false,
    description: null,
    frontName: 'Смартфон Infinix HOT 40 Pro 8/256Gb Palm Blue',
    slug: 'infinix-hot-40-pro-8-256gb-palm-blue',
    brand: 'Infinix',
    catalogId: {
      productId: 'prod7320011',
      skuId: 'sku6600012',
      serialId: null,
    },
    colors: [
      {
        id: 'spec300007',
        name: 'черный',
        code: '#000000',
        catalogIdData: {
          productId: 'prod7320011',
          skuId: 'sku6600014',
          serialId: null,
        },
        skuSlug: 'infinix-hot-40-pro-8-256gb-starlit-black',
      },
      {
        id: 'spec5900010',
        name: 'зеленый',
        code: '#4de4aa',
        catalogIdData: {
          productId: 'prod7320011',
          skuId: 'sku6600013',
          serialId: null,
        },
        skuSlug: 'infinix-hot-40-pro-8-256gb-starfall-green',
      },
      {
        id: 'spec6100008',
        name: 'голубой',
        code: '#abf1fd',
        catalogIdData: {
          productId: 'prod7320011',
          skuId: 'sku6600012',
          serialId: null,
        },
        skuSlug: 'infinix-hot-40-pro-8-256gb-palm-blue',
      },
      {
        id: 'spec1200001',
        name: 'золотой',
        code: '#FFE4B5',
        catalogIdData: {
          productId: 'prod7320011',
          skuId: 'sku6600011',
          serialId: null,
        },
        skuSlug: 'infinix-hot-40-pro-8-256gb-horizon-gold',
      },
    ],
    images: [
      {
        url: '/api/media/asset?mediaId=m6700009',
        main: true,
        path: 'https://msk.tele2.ru/api/media/asset?mediaId=m6700009',
      },
      {
        url: '/api/media/asset?mediaId=m6700010',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6700010',
      },
      {
        url: '/api/media/asset?mediaId=m6700011',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6700011',
      },
      {
        url: '/api/media/asset?mediaId=m6700012',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6700012',
      },
    ],
    price: {
      amount: 16990,
      currency: 'RUB',
    },
    salePrice: null,
    discountValue: null,
    url: null,
    barcode: null,
    eventMessage: {
      id: '1400001',
      name: 'Новинка',
      type: 'new',
      iconColor: null,
      icon: 'https://msk.tele2.ru/api/media/asset?mediaId=m4940001',
      description: null,
    },
    categorySlug: 'smartphones',
    promo: true,
    promoCampaigns: [
      {
        id: '1400002',
        externalId: '15',
        name: 'Комбо 1.0 (-50%)',
        slug: null,
        promoTextNotAuth: 'при покупке комбо 3 в 1',
        promoPageLink: 'https://msk.tele2.ru/promotions/article/discount-infinix-smartphones/discount-infinix-smartphones',
        promoText: null,
        infoBlockTitle: 'Скидка за комплект',
        infoBlockText: 'При покупке смартфона, SIM-карты и страховки',
        infoBlockIcon: 'https://s3.tele2.ru/ds-site/images/shop/combo/50-sale-bage.svg',
        priority: 360,
        displayType: 'text',
        labelText: null,
        labelTextColor: null,
        labelBackgroundColor: null,
        tooltipText: null,
      },
    ],
    saleVariants: [
      {
        catalogId: {
          productId: 'prod6820001',
          skuId: 'sku6140006',
          serialId: null,
        },
        skuType: 'comboSku',
        promoCampaigns: [
          {
            id: '1400002',
            externalId: '15',
            name: 'Комбо 1.0 (-50%)',
            slug: null,
            promoTextNotAuth: 'при покупке комбо 3 в 1',
            promoPageLink: 'https://msk.tele2.ru/promotions/article/discount-infinix-smartphones/discount-infinix-smartphones',
            promoText: null,
            infoBlockTitle: 'Скидка за комплект',
            infoBlockText: 'При покупке смартфона, SIM-карты и страховки',
            infoBlockIcon: 'https://s3.tele2.ru/ds-site/images/shop/combo/50-sale-bage.svg',
            priority: 360,
            displayType: 'text',
            labelText: null,
            labelTextColor: null,
            labelBackgroundColor: null,
            tooltipText: null,
          },
        ],
        salePrice: null,
      },
    ],
  },
  {
    article: '0100-498389',
    pickupAvailable: true,
    deliveryAvailable: true,
    description: null,
    frontName: 'Смартфон Infinix HOT 40i 4/128Gb Starlit Black',
    slug: 'infinix-hot-40i-4-128gb-starlit-black',
    brand: 'Infinix',
    catalogId: {
      productId: 'prod7220033',
      skuId: 'sku6490037',
      serialId: null,
    },
    colors: [
      {
        id: 'spec300007',
        name: 'черный',
        code: '#000000',
        catalogIdData: {
          productId: 'prod7220033',
          skuId: 'sku6490037',
          serialId: null,
        },
        skuSlug: 'infinix-hot-40i-4-128gb-starlit-black',
      },
      {
        id: 'spec1200001',
        name: 'золотой',
        code: '#FFE4B5',
        catalogIdData: {
          productId: 'prod7220033',
          skuId: 'sku6490035',
          serialId: null,
        },
        skuSlug: 'infinix-hot-40i-4-128gb-horizon-gold',
      },
      {
        id: 'spec6100008',
        name: 'голубой',
        code: '#abf1fd',
        catalogIdData: {
          productId: 'prod7220033',
          skuId: 'sku6490036',
          serialId: null,
        },
        skuSlug: 'infinix-hot-40i-4-128gb-palm-blue',
      },
    ],
    images: [
      {
        url: '/api/media/asset?mediaId=m6590038',
        main: true,
        path: 'https://msk.tele2.ru/api/media/asset?mediaId=m6590038',
      },
      {
        url: '/api/media/asset?mediaId=m6590039',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6590039',
      },
      {
        url: '/api/media/asset?mediaId=m6590040',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6590040',
      },
      {
        url: '/api/media/asset?mediaId=m6590041',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6590041',
      },
      {
        url: '/api/media/asset?mediaId=m6590042',
        main: false,
        path: 'https://msk.tele2.ru/api/media/content?contentId=m6590042',
      },
    ],
    price: {
      amount: 10990,
      currency: 'RUB',
    },
    salePrice: null,
    discountValue: null,
    url: null,
    barcode: null,
    eventMessage: {
      id: '1400001',
      name: 'Новинка',
      type: 'new',
      iconColor: null,
      icon: 'https://msk.tele2.ru/api/media/asset?mediaId=m4940001',
      description: null,
    },
    categorySlug: 'smartphones',
    promo: true,
    promoCampaigns: [
      {
        id: '2000002',
        externalId: '158',
        name: 'Скидка на смартфоны 500',
        slug: 'smartphones',
        promoTextNotAuth: '500 ₽ скидка – 500 минут ',
        promoPageLink: 'https://msk.tele2.ru/minutes-management/smartphones',
        promoText: '500 ₽ скидка – 250 минут ',
        infoBlockTitle: 'Скидка до 500 ₽ за минуты',
        infoBlockText: 'Скидка за минуты',
        infoBlockIcon: null,
        priority: 100,
        displayType: 'combined',
        labelText: 'Скидка до 500 ₽ за минуты',
        labelTextColor: '#C882FF',
        labelBackgroundColor: '#F4E5FF',
        tooltipText: 'Обменяй минуты на скидку на устройства.',
      },
      {
        id: '1400002',
        externalId: '15',
        name: 'Комбо 1.0 (-50%)',
        slug: null,
        promoTextNotAuth: 'при покупке комбо 3 в 1',
        promoPageLink: 'https://msk.tele2.ru/promotions/article/discount-infinix-smartphones/discount-infinix-smartphones',
        promoText: null,
        infoBlockTitle: 'Скидка за комплект',
        infoBlockText: 'При покупке смартфона, SIM-карты и страховки',
        infoBlockIcon: 'https://s3.tele2.ru/ds-site/images/shop/combo/50-sale-bage.svg',
        priority: 360,
        displayType: 'text',
        labelText: null,
        labelTextColor: null,
        labelBackgroundColor: null,
        tooltipText: null,
      },
      {
        id: '1400003',
        externalId: '160',
        name: 'Скидка на смартфоны 1000',
        slug: 'smartphones',
        promoTextNotAuth: '1000 ₽ скидка – 1000 минут ',
        promoPageLink: 'https://msk.tele2.ru/minutes-management/smartphones',
        promoText: '1000 ₽ скидка – 500 минут ',
        infoBlockTitle: 'Скидка до 1000 ₽ за минуты',
        infoBlockText: 'Скидка за минуты',
        infoBlockIcon: null,
        priority: 120,
        displayType: 'combined',
        labelText: 'Скидка до 1000 ₽ за минуты',
        labelTextColor: '#C882FF',
        labelBackgroundColor: '#F4E5FF',
        tooltipText: 'Обменяй минуты на скидку на устройства.',
      },
    ],
    saleVariants: [
      {
        catalogId: {
          productId: 'prod6820001',
          skuId: 'sku6140006',
          serialId: null,
        },
        skuType: 'comboSku',
        promoCampaigns: [
          {
            id: '1400002',
            externalId: '15',
            name: 'Комбо 1.0 (-50%)',
            slug: null,
            promoTextNotAuth: 'при покупке комбо 3 в 1',
            promoPageLink: 'https://msk.tele2.ru/promotions/article/discount-infinix-smartphones/discount-infinix-smartphones',
            promoText: null,
            infoBlockTitle: 'Скидка за комплект',
            infoBlockText: 'При покупке смартфона, SIM-карты и страховки',
            infoBlockIcon: 'https://s3.tele2.ru/ds-site/images/shop/combo/50-sale-bage.svg',
            priority: 360,
            displayType: 'text',
            labelText: null,
            labelTextColor: null,
            labelBackgroundColor: null,
            tooltipText: null,
          },
        ],
        salePrice: null,
      },
    ],
  },
];

export { devicesData, devicesArray };
